# DO NOT CHANGE THIS VALUE! INTERNAL USAGE
config-version: 1

# How many seconds are between shooting stars. Only integers allowed
time-per-shooting-star: 45

# Only spawn shooting stars when the time is between 13000 and 23000. Only booleans allowed.
only-night: true

# Only spawn shooting stars in overworld typed dimensions. Only booleans allowed.
only-overworld: true

# Automatically disable when the tps drops to <16. Only booleans allowed.
auto-disable-on-lag: true
